"""Change column name because column wil store profile photo path

Revision ID: 52ebf5c11c0d
Revises: 08cad88fc104
Create Date: 2020-05-07 13:11:02.692293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ebf5c11c0d'
down_revision = '08cad88fc104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_path', sa.String(), nullable=True))
    op.drop_column('users', 'profile_photo_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_photo_path')
    # ### end Alembic commands ###
